name: Action Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files for
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: surendrapadala/hello-world-javascript-action@master
        with:
          who-to-greet: Surendra
      - name: Log Greeting  Time
        run: echo "${{ steps.greet.outputs.time }}"